# Atividade 4

**Objetivo:**  
Desenvolver um programa em Python para *calcular as frequências naturais de vibração e os modos normais (deslocamentos relativos) de uma cadeia atômica finita com 2, 3 e 4 átomos*, incluindo interações com vizinhos mais distantes (segunda vizinhança) no último caso.

 
**Instruções:**
- Cadeia linear com 2 massas:  
    - Modele uma cadeia com duas massas $m_1$ e $m_2$ conectadas por uma mola de constante $k$.
    - Ambas as extremidades são livres (não ligadas a paredes).
    - Estude os efeitos da diferença entre $m_1$ e $m_2$ nas frequências e nos deslocamentos relativos.  

- Extensão para 3 massas:  
    - Conecte três massas em linha com molas entre elas.
    - Varie as massas e analise o comportamento vibracional do sistema.
    - Mantenha as extremidades livres.

- Extensão para 4 massas com inclusão de segunda vizinhança:  
    - Agora, modele uma cadeia com quatro massas $m_1$, $m_2$, $m_3$, $m_4$, conectadas por molas com constante $k$ entre vizinhos imediatos.
    - Adicione molas adicionais conectando pares de massas a duas posições de distância:
        - Entre $m_1$ e $m_3$;
        - Entre $m_2$ e $m_4$.
    - Use uma constante $k’$ para as molas de segunda vizinhança (ex: $k’ = 0.2k, 0.5k,$ etc.).

**Análise:**
- Como a presença de segunda vizinhança altera as frequências naturais
- Quais modos normais são mais afetados por essas interações adicionais.  
 

**Visualizações Recomendadas:**
- Gráficos das frequências naturais para cada configuração;
- Visualização dos modos normais (vetores de deslocamento);
- Comparação entre o caso com e sem interações de segunda vizinhança para 4 átomos.

**Entrega Esperada:**
- Código funcional e bem comentado
- Gráficos claros dos resultados
-Texto explicativo (até 300 palavras) discutindo:
    - O efeito da variação das massas;
    - O impacto da inclusão de segundos vizinhos;
    - A interpretação física das modificações observadas nos modos.

###### 

In [18]:
import matplotlib.pyplot as plt
import numpy as np
from vpython import *

## Montando a matriz

$D_{j,j\pm 1} = \frac{-K_{j,j\pm 1}}{m_j}$, $\hspace{1cm}$   $D_{j, j} = \frac{K_{j, j-1} + K_{j, j+1}}{m_j}$

### D para n = 2

In [72]:
k, m1, m2 = 1, 2, 1 #constantes genéricas

M2 = np.vstack([
    np.full(2, 1/m1),
    np.full(2, 1/m2)])


D2 = np.array([[k/m1, -k/m1],
              [-k/m2, k/m2]])
valor, vetor = np.linalg.eigh(D2)
print(f"Matriz D: \n{D2} \n \nFrequências: {valor} \n \nModos normais: \n{vetor}")

Matriz D: 
[[ 0.5 -0.5]
 [-1.   1. ]] 
 
Frequências: [-0.28077641  1.78077641] 
 
Modos normais: 
[[-0.78820544 -0.61541221]
 [-0.61541221  0.78820544]]


In [ ]:
M2 = np.vstack([
    np.full(2, 1/m1),
    np.full(2, 1/m2)])


K = np.array([[k, -k],
              [-k, k]])

M2*K

array([[ 0.5, -0.5],
       [-1. ,  1. ]])

In [ ]:
#primeiro montamos a matriz M
massas = input("Qual o número de massas da cadeia?")
m = []
for i in range(int(massas)): 
    m_var = input(f"Qual a massa m{i+1}?")
    m.append(float(m_var))
m = np.array(m)
#mc = m.reshape(-1, 1)
U = np.full((len(m), len(m)), 1)
K = m.reshape(-1, 1)*U

In [99]:
print(U)
print(K)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [ ]:
#cria a matriz nula
massas = int(input("Qual o número de massas da cadeia?"))
m = []
for i in range(int(massas)): 
    m_var = input(f"Qual a massa m{i+1}?")
    m.append(float(m_var))
m = np.array(m)
m0 = np.zeros((massas, massas))
#agora substituimos k
k1 = float(input("Qual a constante elástica k?"))
if massas == 2: 
    D = np.array([[k1/m[0], -k1/m[0]],
                  [-k1/m[1], k1/m[1]]])
else:
    D = m0
    for j in range(n):
        # Diagonal
        Ke = K[j, j-1] if j > 0 else 0  # K_{j,j-1} (0 at boundary)
        Kd = K[j, j+1] if j < n-1 else 0  # K_{j,j+1} (0 at boundary)
        D[j, j] = (Ke + Kd) / m[j]

        # Off-diagonal elements D_{j,j±1}
        if j > 0:
            D[j, j-1] = -K[j, j-1] / m[j]  # D_{j,j-1}
        if j < n-1:
            D[j, j+1] = -K[j, j+1] / m[j]  # D_{j,j+1}

 


print(f"para {massas} massas m_i = {m} e constante elástica k={k1}, a matriz D é: \n{D}")
  


para 4 massas m_i = [1. 1. 1. 1.] e constante elástica 2.0, a matriz D é: 
[[ 1. -1.  0.  0.]
 [-2.  4. -2.  0.]
 [ 0. -3.  6. -3.]
 [ 0.  0. -4.  4.]]


In [133]:
#cria a matriz nula
massas = int(input("Qual o número de massas da cadeia?"))
m = []
for i in range(int(massas)): 
    m_var = input(f"Qual a massa m{i+1}?")
    m.append(float(m_var))
m = np.array(m)
m0 = np.zeros((massas, massas))
#agora substituimos k
k1 = float(input("Qual a constante elástica k?"))
if massas == 2: 
    D = np.array([[k1/m[0], -k1/m[0]],
                  [-k1/m[1], k1/m[1]]])
else:
    D = m0
    for k in range(n-1):
        D[k, k+1] = -k1/m[k]
        D[k+1, k] = -k1/m[k+1]

    for j in range(n):
        if j == 0 or j == n-1:
            D[j, j] = k1/m[j]
        else:
            D[j, j] = (D[j, j-1] + D[j, j+1])/m[j]
newD = D        
    
 


print(f"para {massas} massas m_i = {m} e constante elástica k={k1}, a matriz D é: \n{newD}")

para 6 massas m_i = [1. 1. 1. 1. 1. 1.] e constante elástica k=3.0, a matriz D é: 
[[ 3. -3.  0.  0.  0.  0.]
 [-3. -6. -3.  0.  0.  0.]
 [ 0. -3. -6. -3.  0.  0.]
 [ 0.  0. -3.  3.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


### Para n = 3

In [51]:
k, m1, m2, m3 = 1, 1, 1, 1 #constantes genéricas

M3 = np.vstack([np.full(n, m1),
                np.full(n, m2),
                np.full(n, m3)])

D3 = np.array([[k/m1, -k/m1, 0],
               [-k/m2, k/m2, 0],
               [0, -k/m3, k/m3]])
valor, vetor = np.linalg.eigh(D3)
print(f"Matriz D: \n{D3} \n \nFrequências: {valor} \n \nModos normais: \n{vetor}")

Matriz D: 
[[ 1. -1.  0.]
 [-1.  1.  0.]
 [ 0. -1.  1.]] 
 
Frequências: [-0.41421356  1.          2.41421356] 
 
Modos normais: 
[[ 5.00000000e-01 -7.07106781e-01 -5.00000000e-01]
 [ 7.07106781e-01  1.00272123e-16  7.07106781e-01]
 [ 5.00000000e-01  7.07106781e-01 -5.00000000e-01]]


In [52]:
M3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Para n = 4

In [ ]:
k, m1, m2, m3, m4 = 1, 1, 1, 1, 1 #constantes genéricas

M4 = np.vstack([np.full(N, m1),
                np.full(N, m2),
                np.full(N, m3),
                np.full(N, m4)])

D4 = np.array([[k/m1, -k/m1,    0,      0],
               [-k/m2, 2*k/m2, -k/m2,   0],
               [0,    -k/m3,    2*k/m3, 0],
               [0,      0,     -k/m4,  k/m4]])
valor, vetor = np.linalg.eigh(D4)
print(f"Matriz D: \n{D4} \n \nFrequências: {valor} \n \nModos normais: \n{vetor}")

Matriz D: 
[[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2.  0.]
 [ 0.  0. -1.  1.]] 
 
Frequências: [-9.74614466e-17  5.85786438e-01  2.00000000e+00  3.41421356e+00] 
 
Modos normais: 
[[-0.5         0.65328148  0.5        -0.27059805]
 [-0.5         0.27059805 -0.5         0.65328148]
 [-0.5        -0.27059805 -0.5        -0.65328148]
 [-0.5        -0.65328148  0.5         0.27059805]]


In [ ]:
N = 4
M4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Para n = 4 considerando $2^a$ vizinhança

In [68]:
k1, k2, m1, m2, m3, m4 = 1, 1, 1, 1, 1, 1 #constantes genéricas

M4 = np.vstack([np.full(N, m1),
                np.full(N, m2),
                np.full(N, m3),
                np.full(N, m4)])

D4_v = np.array([[(k1 + k2)/m1, -k1/m1,    -k2,      0],
               [-k/m2, (2*k1 + k2)/m2, -k1/m2,   -k2/m2],
               [-k2,    -k/m3,    (2*k1 + k2)/m3, -k1/m3],
               [0,      -k2/m4,     -k1/m4,  (k1 + k2)/m4]])
valor, vetor = np.linalg.eigh(D4_v)
print(f"Matriz D: \n{D4_v} \n \nFrequências: {valor} \n \nModos normais: \n{vetor}")

Matriz D: 
[[ 2. -1. -1.  0.]
 [-1.  3. -1. -1.]
 [-1. -1.  3. -1.]
 [ 0. -1. -1.  2.]] 
 
Frequências: [-9.64506253e-16  2.00000000e+00  4.00000000e+00  4.00000000e+00] 
 
Modos normais: 
[[-5.00000000e-01  7.07106781e-01  4.97655806e-01 -4.83600990e-02]
 [-5.00000000e-01 -2.91659768e-17 -5.66047314e-01 -6.55431491e-01]
 [-5.00000000e-01  3.58693823e-17 -4.29264298e-01  7.52151689e-01]
 [-5.00000000e-01 -7.07106781e-01  4.97655806e-01 -4.83600990e-02]]


In [ ]:
# A matriz para a cadeia de n massas tem tamanho nxn, 
D = np.zeros((n, n))
# Subsituimos os elementos na matriz nula
# para encontrar cada Djj usamos as fórmulas acima

      

In [12]:
print(D)

[[0. 0.]
 [0. 0.]]


# Teste vpython
##### não executa no meu pc :)

In [1]:
%pip install vpython
%load_ext autoreload
%autoreload 2

Note: you may need to restart the kernel to use updated packages.


In [ ]:
from vpython import *
c2 = canvas(width=800, height=500, background=color.black, title='A second canvas')
bola = sphere(pos=vector(-5,0,0), radius=0.5, color=color.red, velocity=vector(10,0,0))
muro = box(pos=vector(0,0,0), size=vector(1,50,1), color=color.blue, axis=vector(0,0,0))
pointer = arrow(pos=vector(bola.pos.x,0,0), axis=vector(10,0,0))
f1=gcurve(color=color.red)
v1 = gcurve(color=color.cyan)
dt=0.01
t=0
while t<3:
    rate(100)
    bola.pos.x=bola.pos.x+bola.velocity.x*dt
    t=t+dt
    pointer.pos.x=bola.pos.x

    if(bola.pos.x>=muro.pos.x):
        bola.velocity.x=-bola.velocity.x
        pointer.axis.x=bola.velocity.x
    v1.plot(t, bola.velocity.x)
    f1.plot(t, bola.pos.x)


In [ ]:
from vpython import *

def deslocar(corpo):
     global dt
     queda = True
     p = corpo.traj.point(corpo.traj.npoints-1)['pos']
     corpo.pos += dt*corpo.v + dt**2*corpo.a/2.
     if corpo.v.y < 0 and corpo.pos.y < corpo.radius:
         if p.y != corpo.pos.y:
             f = (p.y - corpo.radius)/(p.y - corpo.pos.y)
             corpo.pos -= (1 - f)*(corpo.pos - p)
             corpo.v += f*dt*corpo.a
             corpo.t += f*dt
         queda = False
     else:
         corpo.t += dt
         corpo.v += dt*corpo.a
     corpo.traj.append(pos=vec(corpo.pos))
     corpo.d += mag(corpo.pos - p)
     return queda

def resultados(corpo):
     p0 = corpo.traj.point(0)['pos']
     alcance = corpo.pos.x - p0.x
     velocidade = corpo.d / corpo.t
     scene.caption += '<b>'+corpo.legenda+'</b>\n'
     scene.caption += 'Tempo de voo         = {:.2f} s\n'.format(corpo.t)
     scene.caption += 'Alcance horizontal   = {:.2f} m\n'.format(alcance)
     scene.caption += 'Distância percorrida = {:.2f} m\n'.format(corpo.d)
     scene.caption += 'Velocidade média     = {:.2f} m/s\n'.format(velocidade)
     return

def projetar(corpo, vel, ang, leg):
     corpo.v = vel*vec(cos(ang*pi/180.), sin(ang*pi/180.), 0)
     corpo.t = corpo.d = 0
     corpo.legenda = leg
     corpo.traj = curve(pos=vec(corpo.pos),color=corpo.color)

scene = canvas(title = '<h1>Lançamento de projéteis no ar</h1>',
                forward=vec(-0.5,-0.2,-1))
scene.caption = ''
a = 47.
dt = 0.01
g = vec(0,-9.8,0)
q1 = q2 = q3 = True

bola1 = sphere(pos=vec(-7.5,0.2,1), radius=0.4, color=vec(0.93,1,0.16))
bola2 = sphere(pos=vec(-7.5,0.1,0), radius=0.2, color=vec(1,0,0))
bola3 = sphere(pos=vec(-7.5,0.1,-1), radius=0.2, color=vec(1,0.49,0.05))
chao = box(pos=vec(0,-0.1,0), size=vec(16,0.2,10), texture=textures.wood)
parede = box(pos=vec(0,2.8,-5.05),size=vec(16,6,0.1), color=vec(0.7,0.7,0.7))
sitio = text(pos=vec(0,2.8,-5), text='def.fe.up.pt', color=color.blue,
              align='center', depth=0)
projetar (bola1, 12, 45., 'Bola de ténis')
projetar (bola2, 12, 45., 'Sem resistência do ar')
projetar (bola3, 12, 45., 'Bola de ping-pong')
bola2.a = g

while q1 or q2 or q3:
    rate(100)
    bola1.a = g - 0.01606*mag(bola1.v)*bola1.v
    bola3.a = g - 0.14176*mag(bola3.v)*bola3.v
    if q1: q1 = deslocar (bola1)
    if q2: q2 = deslocar (bola2)
    if q3: q3 = deslocar (bola3)

resultados(bola2)
resultados(bola1)
resultados(bola3)